version: '3.3'

services:
  back:
    container_name: back
    image: taehopark/yeojung-back
    build:
      context: BackEnd
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    networks:
      - jenkins-network

networks:
  jenkins-network:
    external: true
